### ISSUE TITLE
parameter types not matching between trait implementation and definition

### ISSUE THREAD

**Issue by vaskur** [Antti/rust-amqp#17]
Hi,

I just tried to use this crate in a minimalist example. I included the 0.0.10 release via cargo.

On running cargo run (or build) I get the result:
error: aborting due to 64 previous errors
Could not compile `amqp`.

All these errors come from protocol.rs and look like
error: method `encode` has an incompatible type for trait:
 expected enum `core::result::Result`,
    found struct `collections::vec::Vec` [E0053]

I tried with rustc 1.3, 1.4 and 1.5.

Am I doing something wrong?

**Comment by Antti** [comment]
Hi,

Sorry, it could be that the version `0.0.10` in cargo is broken,
can you try version `0.0.11` or maybe the version from the github.

**Comment by vaskur** [comment]
That solved the issue. Version 0.0.11 in cargo doesn't have that problem. Thanks a lot for the fast response. :)
