### ISSUE TITLE
channel rpc and async messages

### ISSUE THREAD

**Issue by davidszotten** [Antti/rust-amqp#18]
trying to run what is mostly the `consumer.rs` example. however, if i bind to a queue which already has messages, i get an error `Err(Protocol("Unexpected method frame: basic.deliver, expected: basic.consume-ok"))`

i think the issue is the second basic_consume, which expects the very next message from the server to be the `consume-ok`, but since we've already started consuming, the server is already sending us messages

**Comment by Antti** [comment]
@davidszotten you are right.
We need to handle `synchronous` and `asynchronous` methods differently.
Synchronous methods are marked in `amqp-rabbitmq-0.9.1.json`, all other must be asynchronous.

Probably we should pass over asynchronous methods in the `rpc` calls, so they would be handled elsewhere (in the consumers).

**Comment by Antti** [comment]
There's bunch of methods which require special async handling, most of them are from `basic` class:

```
Async: basic:ack
Async: basic:deliver
Async: basic:get-empty
Async: basic:nack
Async: basic:publish
Async: basic:recover-async
Async: basic:reject
Async: basic:return
Async: connection:blocked
Async: connection:unblocked
```

**Comment by Antti** [comment]
The current workaround (until we fix this) would be to declare consumers on a different channels.

**Comment by Antti** [comment]
@davidszotten I've commited a patch, which should fix this problem, can you test please?

**Comment by davidszotten** [comment]
hey, thanks! will give it a whirl. (may take a little while, this is only for a side-project)

**Comment by davidszotten** [comment]
works great, thanks!
