### ISSUE TITLE
handle_delivery got body content many \0 data

### ISSUE THREAD

**Issue by liutaihua** [Antti/rust-amqp#22]
e.g.
I send msg to queue: "hello world"

rust-amqp it handle it to my handle_delivery,  print the body as string, got this:
Ok("hello world\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}......")
many 0 end of my str.

is there any argument to trim this at call lib?

**Comment by Antti** [comment]
Are you sure you are not sending messages with lots of zeroes at the end?
If you just want to trim strings, you can use: `"foo\u{0}".trim_right_matches("\u{0}")`

**Comment by liutaihua** [comment]
yeah, i'm sure.
i run test with my go-lang script, e.g.
2015/11/18 17:51:24 Received a message: hello world
with the same sender

use rabbitmq exchange type: direct, and  assign a routingkey for queue when queue_bind func

**Comment by Antti** [comment]
Sorry, I can't reproduce the described behaviour,
can you give me a code snippet, where it shows a problem?

**Comment by liutaihua** [comment]
rust new consumer with amqp
```  
  let mut session = Session::new(Options{vhost: "/", host: "host_addr", port: 5672, login: "guest", password: "guest", .. Default::default()})
            .ok()
            .expect("Can't create session");
    let mut channel = session.open_channel(1).ok().expect("Error openning channel 1");

    let queue_name = "";
    let queue_declare = channel.queue_declare(queue_name, false, true, false, false, false, Table::new());
    channel.basic_prefetch(10).ok().expect("Failed to prefetch");
    channel.queue_bind(queue_name, "mydirect", "my_routingkey", false, Table::new());
    let my_consumer: MyConsumer = Default::default();
    let consumer_name = channel.basic_consume(my_consumer, queue_name, "", false, false, false, false, Table::new());
```

and MyConsumer's handle_delivery, just copy the consumer example from repo: 
```
fn handle_delivery(&mut self, channel: &mut Channel, deliver: protocol::basic::Deliver, headers: protocol::basic::BasicProperties, body: Vec<u8>){
info!("[struct] Content body: {:?}", body);
info!("body length: {}", body.len());
}
```

publish "hello world" to Rabbitmq
the rust result:
2015/11/20 17:43:08.567093000-INFO: [struct] Content body: [104, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
2015/11/20 17:51:26.718493000-INFO: body length: 512

**Comment by liutaihua** [comment]
I'm so sorry!
I use a incorrect sender, and the go-lang printf trim the zero byte automatic, holy shit.

thanks for your reply
