### ISSUE TITLE
Fails to connect unless URL has trailing //

### ISSUE THREAD

**Issue by jonnor** [Antti/rust-amqp#33]
For instance both `amqp://localhost` and `amqp://localhost` fails, where as `amqp://localhost//` succeeds.

**Comment by jonnor** [comment]
It also seems to panic:
`panicked at 'outport setup failed: Protocol("Unexpected method frame: channel.close, expected: exchange.declare-ok"`

**Comment by emk** [comment]
This appears to be a problem with how the default vhost is handled, judging from my RabbitMQ logs.

**Comment by andrenth** [comment]
I believe the default vhost should be `"/".to_string()`. This also causes a panic when `Session::new()` is used without passing the `vhost` option explicitly.

**Comment by whitfin** [comment]
I filed a PR to fix this in #68 - appreciate any feedback you guys might have (and if you want to test it out, go ahead).

**Comment by emk** [comment]
Thank you for this PR!
