### ISSUE TITLE
AMQPError is private

### ISSUE THREAD

**Issue by emk** [Antti/rust-amqp#41]
Thank you for your work on AMQP bindings for Rust! I'm looking forward to using these in a project soon.

I noticed (while trying to set up `error-chain`) that the `AMQPError` and `AMQPResult` type are never exported from the `amqp` crate. This makes it difficult to store them inside other error types and propagate them up the call chain.

This could be fixed by adding `pub use amqp_error::AMQPError;` to your `lib.rs` file. I'd be happy to prepare a PR if you're interested.

**Comment by emk** [comment]
This is actually fixed in debd11195a74aa576a58aabfb1577de8ddd04a03, but it hasn't been released to crates.io yet.

**Comment by Antti** [comment]
It is released in v0.0.20.

**Comment by emk** [comment]
Thank you!
