### ISSUE TITLE
Split generated code to another crate

### ISSUE THREAD

**Issue by Keruspe** [Antti/rust-amqp#54]
It could be interresting to have all the codegen stuff in another crate like "amq-protocol" or such (that's the name used for the equivalent ruby gem)

**Comment by Antti** [comment]
@Keruspe Just found this open issue and found your repo.
I actually started doing this myself few hours ago and then found your crate with the same name.
Something mythical going on.
https://github.com/Antti/rust-amq-protocol

**Comment by Keruspe** [comment]
Heh, I needed to do some low level rabbitmq debugging so I gave it a go, trying to make it more flexible and not using ruby. (hte main stuff is in amq-protocol-codegen)

**Comment by Antti** [comment]
Interesting. I was also working on removing ruby. I see you use serde, which is cool.
I implemented all the protocol parsing using macros now, ruby is used to generate some macro-calls.

It's amazing how we even named the crate with the same name. The same date, the same idea. Wow
