### ISSUE TITLE
Session::open_url does not remove the leading '/' in the vhost

### ISSUE THREAD

**Issue by divarvel** [Antti/rust-amqp#8]
See #4

**Comment by Antti** [comment]
From https://www.rabbitmq.com/uri-spec.html

The vhost component is used as the basis for the virtual-host field of the connection.open AMQP method. Any percent-encoded octets in the vhost should be decoded before the it is passed to the server.

Note that:


> The vhost component of the URI does not include the leading "/" character from the path. This makes it possible to refer to any vhost, not only those that begin with a "/" character.
> The vhost is a single segment. Therefore, any "/" characters that appear in the vhost name must be percent-encoded. URIs with multi-segment paths do not obey this specification. (They are reserved to allow future revisions of this URI scheme to refer to AMQP entities other than vhosts.)
> The vhost component may be absent; this is indicated by the lack of a "/" character following the amqp_authority. An absent vhost component is not equivalent to an empty (i.e. zero-length) vhost name.

**Comment by divarvel** [comment]
I'll add percent-decoding to the mix, then.

**Comment by divarvel** [comment]
The PR fixes this issue (I've tested it on a local cluster), but it still doesn't work on on Cloud AMQP (it must be for a different reason)

**Comment by Antti** [comment]
@divarvel Found it! It was `channel_max_limit`. Will push change now.
